name: CI

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: ['ros-iron', 'ros-rolling']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        cache: 'pip'

    - name: Install pip dependencies
      run: |
       python -m pip install --upgrade --upgrade-strategy eager .[test]
       python -m pip freeze

    - name: Run tests
      run: py.test --verbose test
